name: Daily Commit

on:
  schedule:
    - cron: '0 18 * * *'   # 6:00 PM UTC (11:30 PM IST)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update file
        run: |
          echo "Last updated on $(date)" >> log.txt

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Daily auto commit"
          git push